apiVersion: apps/v1
kind: Deployment
metadata:
    name: hello-world-deployment
    labels:
        app: myapp
        type: front-end
spec:
    template: 
        metadata:
            name: mmyapp-pod
            labels: 
                app: myapp
                tipo: front-end
        spec:
            containers:
            - name: nginx-container
              image: nginx
    replicas: 3
    selector:
        matchLabels:
            tipo: front-end